services:
    kuasarr:
        container_name: 'Kuasarr'
        ports:
            - '8080:8080'
        volumes:
            - 'C:\Docker\kuasarr-config:/config:rw'
            - 'C:\Docker\downloads:/downloads:rw'
        environment:
            - 'INTERNAL_ADDRESS=http://192.168.178.207:8080'
            - 'EXTERNAL_ADDRESS=http://192.168.178.207:8080'
        image: 'weedo078/kuasarr:latest'
        restart: unless-stopped
